FROM php:8.1-apache

# Installa estensioni PHP e client MySQL per debug
RUN docker-php-ext-install pdo pdo_mysql
RUN apt-get update && apt-get install -y default-mysql-client

COPY . /var/www/html

EXPOSE 80